const music = [
    {
      "Title": "Pink Venom",
      "artist": "BLACKPINK",
      "album": "Born Pink",
      "release_year": 2022,
      "genre": "K-Pop|Hip-Hop",
      "summary": "A powerful pre-release single from BLACKPINK's 'Born Pink' album, featuring intense beats and strong rap verses.",
      "coverURL": "https://i.scdn.co/image/ab67616d0000b2734e0b12c934e7e46c5e04dc5b",
      "spotify_id": "3qhu5bUymFA3NDU2qjxQj1",
      "youtube_id": "gQlMMD8auMs",
      "duration": 210
    },
    {
      "Title": "How You Like That",
      "artist": "BLACKPINK",
      "album": "The Album",
      "release_year": 2020,
      "genre": "K-Pop|EDM",
      "summary": "BLACKPINK's record-breaking comeback track with a powerful message of resilience and an addictive beat.",
      "coverURL": "https://example.com/how_you_like_that.jpg",
      "spotify_id": "5Fao1A57pOY2LCB4ZP2gCp",
      "youtube_id": "ioNng23DkIM",
      "duration": 200
    },
    {
      "Title": "Kill This Love",
      "artist": "BLACKPINK",
      "album": "Kill This Love",
      "release_year": 2019,
      "genre": "K-Pop|Electropop",
      "summary": "An explosive anthem with bold trumpets and a dramatic beat, expressing the pain of toxic love.",
      "coverURL": "https://i.scdn.co/image/ab67616d0000b27337bca6df7e2e58d9db69d85f",
      "spotify_id": "2Fxmhks0bxGSBdJ92vM42m",
      "youtube_id": "2S24-y0Ij3Y",
      "duration": 192
  },
  {
    "Title": "DDU-DU DDU-DU",
    "artist": "BLACKPINK",
    "album": "Square Up",
    "release_year": 2018,
    "genre": "K-Pop|Hip-Hop",
    "summary": "The song that propelled BLACKPINK to global fame, featuring an iconic chorus and a powerful dance beat.",
    "coverURL": "https://i.scdn.co/image/ab67616d0000b273848b250ce384235a41cf8a5f",
    "spotify_id": "6hvczQ05jc1yGlp9zhb95V",
    "youtube_id": "IHNzOHi8sJs",
    "duration": 209
},
{
  "Title": "Lovesick Girls",
  "artist": "BLACKPINK",
  "album": "The Album",
  "release_year": 2020,
  "genre": "K-Pop|Dance-Pop",
  "summary": "A high-energy yet emotional track that explores the pain and struggles of love.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b2736eb7f0e6a385d905995d1ecf",
  "spotify_id": "3Z8FwOEN59mRMxDCtb8N0A",
  "youtube_id": "dyRsYk0LyA8",
  "duration": 203
},
{
  "Title": "BOOMBAYAH",
  "artist": "BLACKPINK",
  "album": "Square One",
  "release_year": 2016,
  "genre": "K-Pop|EDM",
  "summary": "BLACKPINK's high-energy debut track, featuring an infectious beat and bold lyrics.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b273848b250ce384235a41cf8a5f",
  "spotify_id": "1KpCi9B9ZHEv7l2Sh7j7n5",
  "youtube_id": "bwmSjveL3Lc",
  "duration": 245
},
{
  "Title": "Playing with Fire",
  "artist": "BLACKPINK",
  "album": "Square Two",
  "release_year": 2016,
  "genre": "K-Pop|Tropical House",
  "summary": "A song about the dangers of falling too deeply in love, featuring a fiery beat and emotional lyrics.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b273848b250ce384235a41cf8a5f",
  "spotify_id": "7COXchtUOMd6uIT6HvmRaI",
  "youtube_id": "9pdj4iJD08s",
  "duration": 212
},
{
  "Title": "As If It's Your Last",
  "artist": "BLACKPINK",
  "album": "Single",
  "release_year": 2017,
  "genre": "K-Pop|Dance-Pop",
  "summary": "A fun, energetic track with an addictive melody, showcasing BLACKPINK's playful side.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b273bff4cdaff0f6e50179945cf0",
  "spotify_id": "0s26En1JoJhVj32vizElpA",
  "youtube_id": "Amq-qlqbjYA",
  "duration": 213
},
{
  "Title": "Forever Young",
  "artist": "BLACKPINK",
  "album": "Square Up",
  "release_year": 2018,
  "genre": "K-Pop|Tropical House",
  "summary": "An uplifting song about living life to the fullest, featuring a tropical house beat.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b273848b250ce384235a41cf8a5f",
  "spotify_id": "3l5cwoJvNOMpGz9X0T3I6s",
  "youtube_id": "Etl5XQbj2nM",
  "duration": 231
},
{
  "Title": "Shut Down",
  "artist": "BLACKPINK",
  "album": "Born Pink",
  "release_year": 2022,
  "genre": "K-Pop|Hip-Hop",
  "summary": "A unique fusion of classical music and hip-hop beats, with a strong message of dominance.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b2734e0b12c934e7e46c5e04dc5b",
  "spotify_id": "3qhu5bUymFA3NDU2qjxQj1",
  "youtube_id": "POe9SOEKotk",
  "duration": 180
},
{
  "Title": "Shut Down",
  "artist": "BLACKPINK",
  "album": "Born Pink",
  "release_year": 2022,
  "genre": "K-Pop|Hip-Hop",
  "summary": "A unique fusion of classical music and hip-hop beats, with a strong message of dominance.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b2734e0b12c934e7e46c5e04dc5b",
  "spotify_id": "3qhu5bUymFA3NDU2qjxQj1",
  "youtube_id": "POe9SOEKotk",
  "duration": 180
},
{
  "Title": "Whistle",
  "artist": "BLACKPINK",
  "album": "Square One",
  "release_year": 2016,
  "genre": "K-Pop|Hip-Hop",
  "summary": "A minimalistic beat combined with catchy whistle sounds made this song a massive hit.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b2735cd65b376d558435f9e3ec96",
  "spotify_id": "4lKvl5ZClDGQvrrAd9V3Yh",
  "youtube_id": "dISNgvVpWlo",
  "duration": 212
},
{
  "Title": "As If It's Your Last",
  "artist": "BLACKPINK",
  "album": "Stand-Alone Single",
  "release_year": 2017,
  "genre": "K-Pop|Pop",
  "summary": "A bright and energetic love song that became one of BLACKPINK's most streamed tracks.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b273a3b4ef934df9a91b3c6db3b4",
  "spotify_id": "2ekn2ttSfGqwhhate0LSR0",
  "youtube_id": "Amq-qlqbjYA",
  "duration": 213
},
{
  "Title": "Really",
  "artist": "BLACKPINK",
  "album": "Square Up",
  "release_year": 2018,
  "genre": "K-Pop|R&B",
  "summary": "A smooth and catchy song from BLACKPINK's 'Square Up' EP, featuring emotional lyrics and groovy beats.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b273eb7874db544d4ddfde34561f",
  "spotify_id": "3EXUKLxvVkcIQHXHofYSLV",
  "youtube_id": "bwmSjveL3Lc",
  "duration": 180
},
{
  "Title": "See U Later",
  "artist": "BLACKPINK",
  "album": "Square Up",
  "release_year": 2018,
  "genre": "K-Pop|Dance",
  "summary": "A breakup anthem with a confident attitude, featured in BLACKPINK's 'Square Up' EP.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b273eb7874db544d4ddfde34561f",
  "spotify_id": "4JB2AKF2yBGpRPQ6Po4P9d",
  "youtube_id": "F2g8GdP8D6Q",
  "duration": 190
},
{
  "Title": "Stay",
  "artist": "BLACKPINK",
  "album": "Square Two",
  "release_year": 2016,
  "genre": "K-Pop|Acoustic",
  "summary": "A heartfelt acoustic ballad from BLACKPINK's 'Square Two' album, showcasing emotional vocals.",
  "coverURL": "https://i.scdn.co/image/ab67616d0000b273ee7f954db5585a52159b8494",
  "spotify_id": "3zT9UOhQZpC5rs8KgzxXHb",
  "youtube_id": "FzVR_fymZw4",
  "duration": 240
} 
  ];